---

- name: PUSHGATEWAY | Install
  include: install.yml
  tags:
    - pushgateway_install

- name: PUSHGATEWAY | Configure
  include: config.yml
  tags:
    - pushgateway_configure

- name: PUSHGATEWAY | Service
  include: service.yml
  tags:
    - pushgateway_service
